### ISSUE TITLE
Cant upload animation PSA due to model missing bones.

### ISSUE THREAD

**Issue by EndslayerGaming** [DarklightGames/io_scene_psk_psa#100]
Im going to be honest, im incredibly new to blender and have no idea what im doing 100% of the time, but all the people ive talked to who do the same thing im trying to do with the same models and animations have no problems. Same version of blender and everything. 

"The armature is missing 45 bones that exist ins the PSA"

**Comment by cmbasnett** [comment]
This is not an error per-se, this is a warning that the PSA has more bones than the target armature. The animations have still been imported.
