### ISSUE TITLE
Wrong Bone target (?)

### ISSUE THREAD

**Issue by Mayo-LK** [DarklightGames/io_scene_psk_psa#102]
**Versions**
Blender: (example: Latest Version 4.2)
io_scene_psk_psa: (Latest)

**Describe the bug**
I'm not sure if this is how the PSAs are configured to be or just a wrong targeting, but I'm trying to import PSA files that are face expressions, and it targets the LODs instead of the main bones.

**To Reproduce**
Import the model's head, select the armature then import any facial PSA expression.

**Expected behavior**
Bones are moving but not the mesh.

**Additional context**
I'm not sure if that's how the newest version of UE handles it differently. I'm doing this for porting purposes. It's an MK1 model, so I leave that as food for thought.
[SK_MotaroKAM_Fac
[Laugh.zip](https://github.com/user-attachments/files/16645689/Laugh.zip)
e001.zip](https://github.com/user-attachments/files/16645687/SK_MotaroKAM_Face001.zip)

**Comment by cmbasnett** [comment]
Is there a .config file that comes with this PSA?

**Comment by Mayo-LK** [comment]
_Any updates?_ I haven't got any luck whatsoever, and I'm relying on the answer provided here.
