### ISSUE TITLE
The armature  is missing 15 bones that exist in the PSA

### ISSUE THREAD

**Issue by PengTiShanye** [DarklightGames/io_scene_psk_psa#105]
**Versions**
Blender: 4.2.1
io_scene_psk_psa: all new

**Describe the bug**
The armature 'SK_hys_huijingrenou_03_Lod3' is missing 15 bones that exist in the PSA:
['Bip001-HeadNub', 'Bip001-L-Finger0Nub', 'Bip001-L-Finger1Nub', 'Bip001-L-Finger2Nub', 'Bip001-L-Finger3Nub', 'Bip001-L-Finger4Nub', 'Bip001-L-Toe0Nub', 'Bip001-R-Finger0Nub', 'Bip001-R-Finger1Nub', 'Bip001-R-Finger2Nub', 'Bip001-R-Finger3Nub', 'Bip001-R-Finger4Nub', 'Bip001-R-Toe0Nub', 'ball_l', 'ball_r']

**To Reproduce**
1. import PSA file

**Expected behavior**
Same problem I can't import PSA, these files are exported by UMODEL, from Black Myth Wukong

**Screenshots**

![图片](https://github.com/user-attachments/assets/1f62f3cf-5b0f-40ac-a103-20532962cf1b)

**Files**

[SK_hys_huijingrenou_03.zip](https://github.com/user-attachments/files/16847700/SK_hys_huijingrenou_03.zip)

[Uploading SKEL_hys_huijingrenou_03.zip…]()

**Comment by cmbasnett** [comment]
This is not an error, it is a warning. The animations have been imported.
