### ISSUE TITLE
Multiple psa import

### ISSUE THREAD

**Issue by zavorfang** [DarklightGames/io_scene_psk_psa#106]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to import 100 psa one by one

**Describe the solution you'd like**
Ability to select multiple psa at the file import window.

**Describe alternatives you've considered**
A script that runs the psa import function within a folder.

**Additional context**
None

**Comment by cmbasnett** [comment]
This has already been implemented (#55). You can import multiple PSA files by dragging and dropping the files from the OS file system browser.

This functionality was added in the latest version on the Blender Extensions platform.
