### ISSUE TITLE
"ZIP packaged incorrectly; __init__.py should be in a directory, not at top-level"

### ISSUE THREAD

**Issue by RazorWolvendom** [DarklightGames/io_scene_psk_psa#116]
**Versions**
Blender: 4.1.0
io_scene_psk_psa: v7.1.0

**Describe the bug**
in preferences it simply cant import the addon

**Screenshots**
![ScreenShot_20241111205841](https://github.com/user-attachments/assets/e971416f-a4eb-4358-8f10-12ffb98697ee)
![ScreenShot_20241111205928](https://github.com/user-attachments/assets/0bb499ce-092f-448f-b4bb-a305ac15a723)

**Comment by SamelCamel** [comment]
The most recent release (7.1.0) only works for Blender 4.2. I think the most recent version for 4.1 is version 7.0.0
