### ISSUE TITLE
Support for non-standard chunks and .pskx extension

### ISSUE THREAD

**Issue by floxay** [DarklightGames/io_scene_psk_psa#15]
Hey, I just wanted to ask if you would consider adding support for these chunks;
- FACE3200
- VERTEXCOLOR
- EXTRAUVS%d
- VTXNORMS

**Comment by cmbasnett** [comment]
Absolutely. Could you provide an example file with all of these features utilized?

**Comment by floxay** [comment]
Here's a skeletal mesh with all four of the above mentioned chunks; [CS_Sarge_S0_Skelmesh.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/7937959/CS_Sarge_S0_Skelmesh.zip)

I'm linking the VTXNORMS chunk block just in case since it is not part of 'vanilla' UEViewer, tho it's pretty straightforward; [ExportPsk.cpp#L250-L264](https://github.com/floxay/UEViewer/blob/normals/Exporters/ExportPsk.cpp#L250-L264)

**Comment by cmbasnett** [comment]
@floxay I added PSKX functionality in pull request https://github.com/DarklightGames/io_scene_psk_psa/pull/17.

Could you have a look and see if it works as advertised on whatever models you might have laying around? This link should work: https://github.com/DarklightGames/io_scene_psk_psa/archive/refs/heads/feature-pskx.zip

I will merge it to main once you give it the thumbs up.

**Comment by floxay** [comment]
That was fast! Thank you!

One thing I noticed is the vertex colors being incorrect;
![image](https://user-images.githubusercontent.com/57007485/151120356-40365055-217e-4291-a4e8-cbfbac7762e0.png)

I believe it's due to the lack of conversion between linear and sRGB.

**Comment by floxay** [comment]
Actually I'm not so sure anymore which one is correct, this is what UEViewer shows;
![image](https://user-images.githubusercontent.com/57007485/151123064-2092d803-f08e-4b11-a4ef-46fa7f303176.png)

This -at least to me- looks closer to the one this addon imports ...but that would mean that the other two addons are not working properly or with proper data, or simply the viewer in UEViewer is incorrect.

**Comment by floxay** [comment]
Apologies for the lengthy thread, I believe I've reached the conclusion.

I enabled cooked content for Unreal Engine and compared the results;
![image](https://user-images.githubusercontent.com/57007485/151129843-8f08211b-8d52-41cb-b82d-bd7e316e635a.png)

Looking at the mask and legs it seems that conversion between linear and sRGB is indeed needed and the viewer in UEViewer displays it incorrectly.

**Comment by cmbasnett** [comment]
Interesting. I will add sRGB color conversion as the default behavior later today.

**Comment by cmbasnett** [comment]
Updated the branch with the sRGBA conversion as the default, as well as adding support for toggling the import of additional data.

![image](https://user-images.githubusercontent.com/5035660/151459142-5ac3a37b-795a-4e7f-80d4-8e0210e6ca96.png)

![image](https://user-images.githubusercontent.com/5035660/151459031-818223b1-1e9d-4cbf-a32e-cdfc89c3997a.png)

Give it a whirl if you get a chance.

**Comment by floxay** [comment]
Works flawlessly 👍

**Comment by cmbasnett** [comment]
This has been merged to main and is part of the latest release release (2.1.0)
