### ISSUE TITLE
What version of unreal engine does this work with?

### ISSUE THREAD

**Issue by tijon1** [DarklightGames/io_scene_psk_psa#18]
Hello, I'm trying to export a model to Unreal Engine 2.5 (UT2004) and the bones don't move, the mesh does move though. And that got me wondering, for what version of Unreal Engine is this meant?

**Comment by cmbasnett** [comment]
Sorry for not getting to this earlier.

Our team is using this for Red Orchestra: Ostfront, a derivative of the UT2K4 engine. In theory this should also work with other versions of the engine as well like UE3.

I'm not sure what you mean by the bones not moving but the mesh does. Could you elaborate on the exact problem you're having?

**Comment by cmbasnett** [comment]
Marking as invalid because this is not a proper issue report.
