### ISSUE TITLE
Bones can be exported with names that are not handled correctly by Unreal Engine

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/io_scene_psk_psa#21]
This is more of a compatibility bug than it is a bug with the exporter itself.

If a bone has a name that is not properly serializable by the UT engine, the bone will be present, but will not properly animate. This is likely because the bone names are being serialized as `name` types within the engine, which only allow ASCII alphanumeric, spaces, and underscore characters.

There are a couple of solutions here:

1. Only allow ASCII alphanumeric, spaces, and underscore characters (throw an error)
2. Automatically transform the names of the bones to replace invalid characters.

I'm leaning heavily towards the first solution, since it results in less "magic" and surprises for bone names when it comes to hooking things up in code. I'm not sure if this is a problem with UE3, but I would assume it has the same issue.

**Comment by cmbasnett** [comment]
Fixed in commit edafa1cf on `feature-psk-mesh-wysiwyg`.

This will be merged to main once that branch has been soak tested and is determined to be stable.

**Comment by cmbasnett** [comment]
This is now part of 4.0.0

**Comment by Kinkojiro** [comment]
Just FYI UE3 does allow hyphen "-" so  LeftShoulder-Swivel etc are legitimate bone names in UE3

**Comment by cmbasnett** [comment]
You're right, that's my mistake. I have pushed an updated version that allows hyphens in the bone names: https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/4.0.1
