### ISSUE TITLE
No option to import .psa animation files

### ISSUE THREAD

**Issue by PonPonTheBonBon** [DarklightGames/io_scene_psk_psa#28]
I downloaded the latest 4.2.0 2022-11-25 release, io_scene_pks_psa-master-4.2.0.zip
https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/4.2.0

Importing it to Blender works fine, and psk shows up for import, and psk and psa shows up for export. But psa doesn't show up for import.

Currently trying to import animations for Befzz's version is bugged. This looks promising, and the psk importer works great. But it can't import psa, at least not by default.

![image](https://user-images.githubusercontent.com/96395260/209720103-21bbf6a1-5f6b-4100-adb2-04e38fd67337.png) ![image](https://user-images.githubusercontent.com/96395260/209720128-6fe8d64a-b246-42bb-ab86-61c982071837.png)

**Comment by cmbasnett** [comment]
The PSAs cannot be imported from the Import menu. With an armature selected, go to the Armature Data tab and find the PSA import panel. You can import animations from there.

**Comment by PonPonTheBonBon** [comment]
@cmbasnett Thank you, this makes it show up in the list in Blender. If it isn't too much to ask, I would like additional help.
I can only open one file, even if I select multiple. The list counts the number of sequences, but I can't get more than one to show up. The button to import doesn't do anything other than saying it was imported. Exporting as fbx, the file isn't larger, and importing to Unreal Editor, it doesn't include any animations.

**Comment by cmbasnett** [comment]
Send me the PSK and PSA files you're working with and I can have a look.

It is not currently supported to browse and import animations from multiple PSA files, you must work with one PSA file at a time.

**Comment by cmbasnett** [comment]
I'm closing this as the original poster has not responded and the report does not describe an actual bug.
