### ISSUE TITLE
Handle MRPHINFO and MRPHDATA sections

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/io_scene_psk_psa#33]
Files exported from Hogwarts Legacy have two new data sections: `MRPHINFO` AND `MRPHDATA`.

It's unclear what these are. I need to track down people who are able to do a bit of research for me on what these do and provide sample files to work with.

**Comment by mirh** [comment]
Well...
https://github.com/Befzz/blender3d_import_psk_psa/pull/89

**Comment by halfuwu** [comment]
it's not related to hogwarts legacy specifically, I added them as chunks for any mesh exported with CUE4Parse, all serialization stuff is located here https://github.com/halfuwu/CUE4Parse/blob/master/CUE4Parse-Conversion/Meshes/MeshExporter.cs

**Comment by cmbasnett** [comment]
Shape key importing has been added to version [4.3.0](https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/4.3.0).
