### ISSUE TITLE
PSA Doesn't show up.

### ISSUE THREAD

**Issue by DJan2404** [DarklightGames/io_scene_psk_psa#36]
When I import the batman beyond suit from Arkham City and try to import animations the import psa doesn't show up is this normal?

**Comment by cmbasnett** [comment]
I'm not sure what the symptoms of this bug are. Can you send the PSK/PSA so I can test locally? What do you do mean by "the Import PSA doesn't show up"?

**Comment by DJan2404** [comment]
I'm sorry for not being clear. English is not my native language. What I meant was that when I open Blender and go to File/Import, there's only the psk/pskx button, but there is no option to import psa files. I noticed that your addon can also import animations, so I was surprised to see that this feature is missing.
[batman.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/11787780/batman.zip)

**Comment by cmbasnett** [comment]
What version of Blender and the addon are you using?

**Comment by PunishMints** [comment]
I'm using Blender 3.5.1 and am having the same issue

**Comment by cmbasnett** [comment]
What version of the addon are you using? 
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/faeb8bd1-d1a6-448f-9ce6-ca13dfa98123)

**Comment by RaidVentadorCourier13** [comment]
Got the same issue here.
Using latest released version: 4.3.0
Blender Version: 3.5.1
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/52705052/b5100163-bc41-4f60-b8d8-4c90cbdb11b6)

**Comment by cmbasnett** [comment]
Sorry, on version 4.3.0, the PSA import is actually tucked away in the armature data panel when you have the armature selected.

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/2ddee70d-867a-4693-a65c-0da680237316)

A later version (not yet released) moves it to the File -> Import menu.

**Comment by cmbasnett** [comment]
Closing this as it is not an issue.

The latest pre release version (https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/5.0.0) has the PSA import in the File menu where folks would expect it to be.
