### ISSUE TITLE
NameError: name 'PSX_UL_MaterialPathList' is not defined

### ISSUE THREAD

**Issue by nikita488** [DarklightGames/io_scene_psk_psa#37]
Addon version: 5.0.0
Blender 3.5.1

When you try to enable addon, this error pop up.

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/6237881/5e80b90e-9618-4b3b-a76d-e4eef1f6c2ba)

**Comment by cmbasnett** [comment]
Hi, thanks for the report! I will fix this.

**Comment by cmbasnett** [comment]
The issue has been fixed and the download package for the release has been updated to include the fix. Please let me know if that fixes it for you and I will close the issue.

**Comment by nikita488** [comment]
Yeah, now it's fixed. Thank you!
