### ISSUE TITLE
Question: (Flat?) Bones

### ISSUE THREAD

**Issue by RaidVentadorCourier13** [DarklightGames/io_scene_psk_psa#38]
Kinda stupid question, unless it was already answered, but why (almost) all of the bone tails are always flat/directed in one direction upon importing them? Each of them have different roll values though. FYI: Those are cat legs.

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/52705052/7177de69-56c0-4fe0-9900-5c52de67d5e9)

**Comment by cmbasnett** [comment]
I'm not sure what the question is exactly. That's just the way that the bones are in the PSK that you imported.

Also, are you sure you're using *this* addon to import the PSK? This addon does not change the bone display type to `STICK`.

**Comment by RaidVentadorCourier13** [comment]
> Also, are you sure you're using this addon to import the PSK?

Yes, I'm sure.

I was just wondering why upon importing the model, the Tails of each of bones are not "connected" with for ex. Shin Bone Tail to Foot Bone Head and so on. Head Rotation and Tail Position reset maybe?

Screenshot:
Transform Pivot Mode: Active Element (It's always Head of the Bone)
Transformation Orientation: Normal
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/52705052/e9194c50-6fbb-4a28-a7d3-04196e23bd30)

**Comment by cmbasnett** [comment]
The reason they aren't connected is that the "bone length" doesn't really exist, and the PSK has no way to know if a bone *should* be connected.

The orientation of the bones is also different when imported back in. Years ago I remember trying to have these bones oriented "correctly", but it always ended up screwing things up, and I never really needed them to be oriented exactly the same anyways. For my own projects I do rig re-targeting, so the orientation of the deformation bones is driven by a properly oriented & IK constrained rig.
