### ISSUE TITLE
Importing UE2 PSA going wrong

### ISSUE THREAD

**Issue by N3rdyNerdy** [DarklightGames/io_scene_psk_psa#39]
Trying to import PSA files is not working, the models are from POSTAL 2(UE2) and Killing Floor 1 (UE2.5).

I select the armature and i try to import the PSA:

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/132853380/203dea44-9291-4772-8890-b43b579aeeb1)

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/132853380/0310926a-4e2b-420f-9871-6bc489baa6b2)

no results at all, am i doing something wrong?

the plugin version is 5.0.0 and blender version 3.4.0.

**Comment by cmbasnett** [comment]
Can you send the PSK and PSA?

**Comment by N3rdyNerdy** [comment]
Sure! here it is

[P2&KF1 PSK.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/11951787/P2.KF1.PSK.zip)

**Comment by cmbasnett** [comment]
These all work fine. I suspect you just weren't activating the actions. Here's a video of how I imported them.


https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/aaca2da9-7986-4ef9-9004-1316e72b2c3b

**Comment by cmbasnett** [comment]
@N3rdyNerdy Closing this out since it's not an issue.
