### ISSUE TITLE
Troubleshooting about Import PSA file

### ISSUE THREAD

**Issue by kyle-109** [DarklightGames/io_scene_psk_psa#40]
I installed add-on package, but there is no option about importing .psa file.
I'm using Blender 3.6.0.
Thank you for your effort in maintaining this project.
![PSA](https://github.com/DarklightGames/io_scene_psk_psa/assets/84192139/e01bfae7-e315-42a3-8dbe-ce59afeda507)

**Comment by forMyReason** [comment]
may this will take smooth help for your work! https://github.com/DarklightGames/io_scene_psk_psa/issues/36

**Comment by cmbasnett** [comment]
@kyle-109 You should download the latest  version, it has the PSA import in the export menu. It was moved from the armature data panel in 5.0.0. Let me know if that works for you!
