### ISSUE TITLE
PSA Importing does not work

### ISSUE THREAD

**Issue by AmanGaming** [DarklightGames/io_scene_psk_psa#41]
As the title suggests, unless I am doing something wrong the ability to import PSA does not work, however I can export to PSA no issue I cannot import any PSA onto my selected armature. as the option in the menus does not exist. Looking to hopefully hear back on this soon.

**Comment by cmbasnett** [comment]
You seem to have downloaded the previous version where the PSA import panel is located elsewhere. The latest version (https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/5.0.0) has it in the place you are expecting it. I recommend installing the new version.
