### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Yarnul** [DarklightGames/io_scene_psk_psa#42]
The plugin is not in the list of installed, although I followed the instructions and saw a message about the successful completion of the installation. Can you please tell me what to do? :(

**Comment by cmbasnett** [comment]
Are you installing it like this?

https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/c464d0f8-4e76-409f-af9a-771492095744

**Comment by Yarnul** [comment]
I repeated all the steps on your video and for some reason now everything worked, although before that I did the same thing. :/
However, thanks a lot for your answer. :)
