### ISSUE TITLE
Issue about Exporting .psk file

### ISSUE THREAD

**Issue by kyle-109** [DarklightGames/io_scene_psk_psa#45]
I am currently using the blender 3.6 version.
The .pskx file is imported via your add-on and extracted as a .psk file, but the file is not created.
The add-on has been updated to the latest version of 5.0.3.

**Comment by cmbasnett** [comment]
Can you send the PSK file in question?

**Comment by cmbasnett** [comment]
@kyle-109 Please provide the PSKX file that seems to have the issue. Without it, I'll have to close the issue since I cannot reproduce the issue.

**Comment by cmbasnett** [comment]
@kyle-109 I'm going to assume that this is no longer an issue and close this since I haven't heard back.
