### ISSUE TITLE
When exporting to PSK: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by PitmanWorksword** [DarklightGames/io_scene_psk_psa#47]
![Picture1](https://github.com/DarklightGames/io_scene_psk_psa/assets/143973662/df3c69fa-6032-4be4-9ce1-2a561241e7d5)
[nissan.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/12508297/nissan.zip)

**Comment by cmbasnett** [comment]
@PitmanWorksword I've fixed this on the main branch and will release a new version very shortly. If you need to work around this in the meantime, simply add an armature object and add an armature modifier to your meshes before exporting.

**Comment by cmbasnett** [comment]
@PitmanWorksword This bug has been fixed in [5.0.5](https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/5.0.5). Thank you for the report!

**Comment by PitmanWorksword** [comment]
Thank you!
