### ISSUE TITLE
"No Sequence Selected"

### ISSUE THREAD

**Issue by Dookster12** [DarklightGames/io_scene_psk_psa#48]
So I attempted to import a PSA Sequence into Blender, and I was greeted with "no sequence selected" instead, Not sure if this is because I did something wrong. I had the skeleton selected and everything!

**Comment by cmbasnett** [comment]
On the import dialog, you must explicitly select which sequences in the PSA you want to import.

**Comment by cmbasnett** [comment]
@Dookster12 Did this solve your issue?

**Comment by cmbasnett** [comment]
I've not received a response so I'm assuming you figured this out. Please file a new report if you run into any more problems.
