### ISSUE TITLE
Blender não importa

### ISSUE THREAD

**Issue by WingGaster** [DarklightGames/io_scene_psk_psa#50]
não consigo importar o arquivo para dentro do blender, ele fica invisivel na aba de ativação, mas dentro da pasta "Addons" ele está la importado e completo.

> Google Translate:
> I can't import the file into Blender, it is invisible in the activation tab, but inside the "Addons" folder it is imported and complete.

**Comment by cmbasnett** [comment]
What version of Blender are you using, and what version of the addon are you using? How did you install the addon?

**Comment by cmbasnett** [comment]
Closing this because there was no response.
