### ISSUE TITLE
Model imports at 100x the scale.

### ISSUE THREAD

**Issue by ettiSurreal** [DarklightGames/io_scene_psk_psa#51]
Unreal's units are centimeters (cm), while Blender's are meters (m) by default. The addon currently doesn't convert from cm to m making the models import at a much higher (exactly 100x) scale.

**Comment by cmbasnett** [comment]
Unreal units are not universally centimetres. For example, Red Orchestra has an unreal unit being 1/60th of a meter. What I suggest to do is to set the screen's unit scale in Blender (https://docs.blender.org/manual/en/latest/scene_layout/scene/properties.html#units) This addon makes a deliberate choice to import the model data as-is, and let the user handle scaling, as there is no one size fits all solution.
