### ISSUE TITLE
Is there a way to convert more than one model?

### ISSUE THREAD

**Issue by samjviana** [DarklightGames/io_scene_psk_psa#52]
Is there a way of converting more than one .psk/.psa at the same time?
I have dozens of .psk, and wanter convert them "at the same time" ... I heard of using python scripting in blender, but I didn't managed to get it working

**Comment by cmbasnett** [comment]
Currently there is no way to do this without scripting. You can use Python to invoke the import operator using this call:

```
bpy.ops.import_scene.psk(filepath=<your_file_path>)
```
