### ISSUE TITLE
no sequences selected

### ISSUE THREAD

**Issue by zedabyu** [DarklightGames/io_scene_psk_psa#54]
Blender: 3.4
io_scene_psk_psa: 5.0.5

Testing out some files from MK1, character Ashrah, imported the body mesh .psk from the Template Mesh folder which was successful but when I import the .psa from the Anim folder, it says 'no sequences selected' 
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/37437558/65de6dd6-5581-4c19-8fba-e8ed727db0b6)

I tried the same using the older plugin from Befzz and the .psa was imported but it mutated the mesh so I decided to try this newer version but it couldn't even import the .psa

Here are the files: https://drive.google.com/drive/folders/1RmVG6A9KuSNyjfK4W50lTvx839RCxRpE?usp=drive_link

Thanks for your help

**Comment by cmbasnett** [comment]
You have to select what sequences you want to import from that PSA file on the import dialog.

**Comment by zedabyu** [comment]
Oh ok thanks, I must have missed it. 
I succesfully imported but the mesh got distorted even though the animation is somewhat working
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/37437558/d400b940-d08b-47f3-9716-33cea06cfea7)

**Comment by cmbasnett** [comment]
What program generated the PSK and PSA files?

**Comment by zedabyu** [comment]
Sorry, not very sure. They were ripped by this person 
https://www.deviantart.com/skarletjomanson/art/MORTAL-KOMBAT-1-3D-MODELS-987393624

**Comment by cmbasnett** [comment]
Alright, I'm going to close this issue since there's nothing for me to do on it. It would seem that the PSAs that were exported are probably incorrect.
