### ISSUE TITLE
Multiple PSA import

### ISSUE THREAD

**Issue by 2ant** [DarklightGames/io_scene_psk_psa#55]
Hi, is it possible to import multiples .psa files at once ? 
When i try to select multiples and then click import it only import the first one.

Thanks for the plugin

**Comment by InPride** [comment]
I am very grateful for your hard work.
But I have over 400 files.
I'm waiting eagerly.

**Comment by cmbasnett** [comment]
> I am very grateful for your hard work. But I have over 400 files. I'm waiting eagerly.

Where are you getting the 400 files from? Are they all individual animations?

**Comment by InPride** [comment]
I'm sure you're having a busy time, but thank you for your quick response.
I extracted the animation of Tales of Arise using FModel. 
When I extracted it with umodel, it was extracted as a file with multiple lists in one file, but some of the animations broke down. So I extracted it with FModel and checked that all the animations came out normally, but it was extracted as multiple files with one animation in one file.
That's why I have more than 400 files.
For now, I'm just loading them one by one with a mouse and keyboard macro.

**Comment by ItsAlphaNeon** [comment]
Same here, multiple file import would be quite a time saver, as I have over 50 animation files per model I need to import. (Over a hundred models total)

Thanks for all the hard work, I hope this becomes a feature eventually

**Comment by cmbasnett** [comment]
This may be possible to handle gracefully in the coming 4.1 release of Blender, where you will now be able to drag & drop multiple files from the file browser into Blender and have them import.

**Comment by InPride** [comment]
Thank you so much for letting me know.  I'm still not finished with the work.  I sincerely hope that only good things happen to you ahead of you.

**Comment by Havaccuis** [comment]
Would be super useful to have a sort of batch import option. Having to do each one manually is pretty rough, especially with high amounts of animations.

**Comment by InPride** [comment]
Now I want to write a batch script that imports all the psa files that are in a particular path to the currently selected amateur. But I think I lack knowledge of Python. By any chance, can you tell me the name and the namespace of the function that I import around everything in that animation when the file path is provided?

**Comment by cmbasnett** [comment]
I'm working on adding the multi drag-and-drop functionality right now.

**Comment by InPride** [comment]
I'm so glad to hear that news. thank you

**Comment by cmbasnett** [comment]
I have added the multi-file drag-and-drop functionality. You can try it out with this. It's not done yet but I won't be able to finish it for a few more days. Let me know if/how this works. Just select all the PSA files & drag & drop them onto the file (in Blender 4.1) [io_scene_psk_psa-psa-import-multiple-7.0.0.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/14817659/io_scene_psk_psa-psa-import-multiple-7.0.0.zip)

**Comment by InPride** [comment]
it work's perfect. i never forget you thanks

**Comment by Rekovari** [comment]
Wait how did you manage to import multiple PSAs? I'm still struggling to figure it out. It only shows 1 in the list and when I try to drag it only imports 1.

**Comment by InPride** [comment]
> Wait how did you manage to import multiple PSAs? I'm still struggling to figure it out. It only shows 1 in the list and when I try to drag it only imports 1.

just delete your psk_psa addon first.
and re import new psk_psa addon from cmbasnett's reply.
will work's with multiple file drag

**Comment by Rekovari** [comment]
> > Wait how did you manage to import multiple PSAs? I'm still struggling to figure it out. It only shows 1 in the list and when I try to drag it only imports 1.
> 
> just delete your psk_psa addon first. and re import new psk_psa addon from cmbasnett's reply. will work's with multiple file drag

Ahhh okay! I see my mistake. I was suppose to drag from the windows explorer window, not from the PSA import blender window. Thanks for clearing that up for me!

**Comment by windshadowruins** [comment]
> I have added the multi-file drag-and-drop functionality. You can try it out with this. It's not done yet but I won't be able to finish it for a few more days. Let me know if/how this works. Just select all the PSA files & drag & drop them onto the file (in Blender 4.1) [io_scene_psk_psa-psa-import-multiple-7.0.0.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/14817659/io_scene_psk_psa-psa-import-multiple-7.0.0.zip)

This drag and drop saved a ton of time. Thank you

**Comment by Fall0uTYT** [comment]
Its not working for me? I drag and drop using the explorer and it doesn't work. I tried to blender window, I tried selecting multiple then exporting. Nothing works.

**Comment by cmbasnett** [comment]
@Fall0uTYT This has been added in the latest version (7.1.2) https://extensions.blender.org/add-ons/io-scene-psk-psa/
