### ISSUE TITLE
Add support for PSA config files

### ISSUE THREAD

**Issue by liuke101** [DarklightGames/io_scene_psk_psa#56]
When I import the psa file with config, the bones are misaligned

**Comment by liuke101** [comment]
What happened to me is consistent with the argument：https://github.com/Befzz/blender3d_import_psk_psa/issues/74

**Comment by cmbasnett** [comment]
This is not currently handled. I looked at the befzz implementation and it looks simple enough, but I generally try to steer clear of trying to handle anything that looks as brittle as that config file format. What program is generating that .config file?

The odd thing is that this seems completely superfluous. To me, it would make more sense for the the program that generates this just fill the relevant bone transforms with zero/identity transforms instead of having an additional ugly sidecar file to parse.

**Comment by cmbasnett** [comment]
I have added the PSA config parsing functionality on a branch (https://github.com/DarklightGames/io_scene_psk_psa/commit/76440affdb795ce0d109dc87da93aae9a9cc603d).

https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/3767ea12-fe81-4355-8c13-0d5af3d18e74

I am looking into why the root bone is flipped around now, although this might be a separate issue.

**Comment by liuke101** [comment]
> I have added the PSA config parsing functionality on a branch ([76440af](https://github.com/DarklightGames/io_scene_psk_psa/commit/76440affdb795ce0d109dc87da93aae9a9cc603d)).
> 
>  2023-11-07.18-39-02.mp4 
> I am looking into why the root bone is flipped around now, although this might be a separate issue.

Great. I'll try it

**Comment by cmbasnett** [comment]
Did this work for you?

**Comment by liuke101** [comment]
> Did this work for you?
Sorry for the late reply, I tried to extract the Blue Protocol game model and I still get an error. I don't quite understand why.

Import PSK:
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/63388681/206aec72-9ee9-4728-ab89-3291535b9851)

Import PSA: Ears and tail collapsed.

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/63388681/9d747f36-30b6-486f-ae97-29a5f29c2645)

**Comment by cmbasnett** [comment]
Could you send that file?

**Comment by liuke101** [comment]
> Could you send that file?
It has been sent to your email with the attachment name E000_00

**Comment by cmbasnett** [comment]
Sorry it must have gotten filtered as spam, can you just post the files here?

**Comment by cmbasnett** [comment]
I have updated the addon to add support for this (https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.1.0). If you into another issue with this, please report a new issue and be sure to upload the files to the issue.
