### ISSUE TITLE
Skeleton not importing correctly?

### ISSUE THREAD

**Issue by Sir-DJ-Cat** [DarklightGames/io_scene_psk_psa#57]
**Versions**
Blender: 4.0
io_scene_psk_psa: 6.0.0

**Describe the bug**
When importing a character PSK model from a UE 3 game (Borderlands 2), the mesh/skeleton does not show up correctly. No errors and non-character (I'm assuming non-skeleton) models work fine.

**To Reproduce**
1. Import the attached model

**Expected behavior**
Should basically look like this: ![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/60939581/cb6d1ef1-6d8b-444d-b334-be97d8e55c5b)

**Screenshots**
But it looks like this: ![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/60939581/cb0ab471-de8a-47f6-81f2-bfc0518814d6)

**Files**
[Skel_Siren000.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/13375940/Skel_Siren000.zip)

**Additional context**
Ripping from Borderlands 2

**Comment by Jdcisnothuman** [comment]
I'm having this problem as well.

**Comment by cmbasnett** [comment]
I tested it locally and it works for me. You have to zoom out though because the model is very large. You can select all and then hit the Frame Selected button (default Numpad .)

**Comment by Sir-DJ-Cat** [comment]
> I tested it locally and it works for me. You have to zoom out though because the model is very large. You can select all and then hit the Frame Selected button (default Numpad .)

Ah yes, I see it now; thanks :)
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/60939581/d0b295bd-6d01-490d-88e6-7ea2878c93a7)
