### ISSUE TITLE
add automatic bone orientation

### ISSUE THREAD

**Issue by Ladisepic** [DarklightGames/io_scene_psk_psa#58]
it would be nice if this addon had automatic bone orientation, its hard to use the rigs when every bone is facing only one direction and is all disconnected and stuff

**Comment by cmbasnett** [comment]
For our game, we had a player rig that we were unable to change, but we wanted to make new animations with a proper IK rig.

What we did was build a new rig on top of the existing rig (in the same object, but different root bones). The deformation bones are then driven by or parented to bones on the new rig. This is a concept related to rig retargetting, which is a whole workflow into itself.

This allows us to work with our own rig without ever really needing to worry about the original deformation bones. It can be a hassle to set up, but the results are worth it. Regardless,  I'm going to have to close this as out of scope.

**Comment by Ladisepic** [comment]
I get it would break animations, but it would be nice for those who dont really want the animations and just want a nicer rig with the model, so you could just leave it in anyways even if its not necessarily compatible with animations (maybe)
