### ISSUE TITLE
UE3 All Imported animation seems to be scaled down?

### ISSUE THREAD

**Issue by MerelyMiserable** [DarklightGames/io_scene_psk_psa#59]
**Versions**
Blender: 4.0
io_scene_psk_psa: 6.0.0

animations for the imported model seem to have been scaled down causing the model to be squashed into a ball

import psk
import psa
play animations
see issue

**Expected behavior**
animations run fine

**Screenshots**
![Capture](https://github.com/DarklightGames/io_scene_psk_psa/assets/77551307/ebabe343-b1cf-4ef1-a4d7-b0caaf390293)

**Files**
Please post attachments of the PSK and/or PSA files that you are using to encounter the bug, if any.
[stuff.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/13421868/stuff.zip)

**Additional context**
the game is Batman Arkham Origins its ue3

**Comment by cmbasnett** [comment]
I believe this is related to #56.

I can push out a patch this weekend that will add support for handling the PSA config sidecar file.

**Comment by cmbasnett** [comment]
I've posted a pre-release version with the functionality needed to import these PSAs correctly. Please check it out here and let me know if this solves your issue: https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.1.0

**Comment by cmbasnett** [comment]
@MerelyMiserable please give this a go when you get a chance.

**Comment by cmbasnett** [comment]
I've received no response, so I'm assuming that this works. I've tested it locally the new version (https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.1.0) fixes the issue. Please re-open another issue if you run into more problems.
