### ISSUE TITLE
Scale import fix

### ISSUE THREAD

**Issue by Dioltwee** [DarklightGames/io_scene_psk_psa#61]
Hello, I would love to suggest an added option to specify scale when importing psk to blender, everything works properly so far, but I have to adjust the scale of the imported models as they are huge, this didn't happen on the previous addon and blender versions.

To solve this I select the hierarchy and diminish the size from 1 to 0.01 and apply scale
Solution is simple but I know it can be automated.

Thank you!

**Comment by cmbasnett** [comment]
My main hang-up with this is that applying a different scale would invalidate the rig for use with any associated PSA files that might be imported (which would likely lead to people reporting bugs about *that* instead). The only way that I would consider adding this is if it just automated the setting of the object scale of the armature, without applying anything.

I have to admit that personally I dislike the idea of even providing the option. The preivous PSK addon had, by default, an automatic scaling down that generated endless headaches for anyone not expecting that particular scaling. I just don't believe that the extra 3 keystrokes it would take to scale the object down is worth automating if it opens the door for more bug reports in the future. For me, as an add-on maintainer, it is easier for me to let the user handling any workflow-specific scaling that doesn't have anything to do with the actual importing of the data.

**Comment by cmbasnett** [comment]
Against my better judgement, I'm going to add this. It will simply set the scale of the top-level object, without applying anything. That way any imported animations will still work.

**Comment by ZennshiZetsumei** [comment]
So.. would it be possible to add something on the import options similar to the way fbx importer has?

I am running into a similar thing where a psk is importing at 100x the size of the animations which is fixed simply by reducing the size of the object to .01 and applying scale/rotation/transforms before importing the psa onto it.

**Comment by Dioltwee** [comment]
@cmbasnett thank you so much for adding that function, is such a good quality of life improvement!

**Comment by cmbasnett** [comment]
This has been implemented and is now in [6.1.2](https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.1.2).
