### ISSUE TITLE
Error when importing .psa to armature

### ISSUE THREAD

**Issue by wr4thful** [DarklightGames/io_scene_psk_psa#64]
**Versions**
Blender: 4.0.2
io_scene_psk_psa: 6.1.0 and 6.0.0 (tried both)

**Describe the bug**
![blender_2024-01-12_19 34 00](https://github.com/DarklightGames/io_scene_psk_psa/assets/143463195/ecde5902-ef5e-40cf-a6aa-865bcdc14ca4)
![blender_2024-01-12_19 32 19](https://github.com/DarklightGames/io_scene_psk_psa/assets/143463195/90c69001-4e87-44fb-a892-7f3e646743d1)

**To Reproduce**

1. Select Armature
2. File > Import > Unreal PSA (.psa)
3. See error

both psk and psa file is exported using latest version of umodel as of now (12/01/2024)
i am aware of what caused the error by the warning mark in blender but i am wondering if this is simply caused by the addon or umodel export itself

hoping to see responses and help, thank you very much :)

**Comment by cmbasnett** [comment]
Can you provide the PSK and PSA you are using to get these warnings?

**Comment by wr4thful** [comment]
hi, thanks for responding. sorry for the late responses, 

heres the psk and psa file
https://www.dropbox.com/scl/fo/xfakqy3zfnguofn1bqyn8/h?rlkey=gfgjwfdwjsyqsvk1c693omkdm&dl=0

please let me know if u had trouble accessing the file

**Comment by cmbasnett** [comment]
The `ThirdPersonRun.psa` seems to be for a completely different rig than the one in the PSK. There are no matching bones, which is a pretty telltale giveaway that the two files aren't meant to work together.

**Comment by wr4thful** [comment]
okay i understand, but the `LV_Character01_Run.psa` are meant to work together right? cus theyre obtained from same directory.
i assume issue came from umodel export itself because the game is small and not very popular and the process may have not been properly optimized. but i thought i just came here to ask if theres anything that can be done to solve it or any workarounds

**Comment by cmbasnett** [comment]
Yes, `LV_Character01_Run.psa` works fine with it, I tested it myself.

**Comment by Equbuxu** [comment]
> that is strange, sadly it doesnt work for me with any of the `.psa`

I'm getting the same error when trying to import a different file (can't post it sadly), deleting the corresponding `.config` file resolves it

**Comment by cmbasnett** [comment]
Yea, the issue here is that the .config file is not a correctly formatted [INI file](https://en.wikipedia.org/wiki/INI_file), so the script fails to parse it. Deleting the .config file will resolve the immediate error. I will look into adding special handling for UEViewer's broken file formatting.

**Comment by cmbasnett** [comment]
@Equbuxu @wr4thful I've published a new version that should fix this issue.

https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.1.1

Please give this a try and let me know if this resolved the issue for you.

**Comment by wr4thful** [comment]
just tried the new version and it gives this error 

![blender_2024-01-21_20 50 04](https://github.com/DarklightGames/io_scene_psk_psa/assets/143463195/231bd1f6-664d-4af9-858e-e571bf48a807)

deleting the corresponding `.config` file does makes the process succesfull, but i dont see any keyframe in blender timeline or any animation strips in the NLA editor. the object pose also did not change at all and im not entirely sure how to check if the animation set is there or not.

**Comment by cmbasnett** [comment]
Please send the files you are using for this, otherwise I can't reproduce your problem.

> but i dont see any keyframe in blender timeline or any animation strips in the NLA editor. the object pose also did not change at all and im not entirely sure how to check if the animation set is there or not.

https://github.com/DarklightGames/io_scene_psk_psa#why-cant-i-see-the-animations-imported-from-my-psa

**Comment by wr4thful** [comment]
hey man after carefully checking everything i realized the addon actually succesfully imports the `.psa` even though theres an error pop up like i posted in last screenshots. after following the instruction from the FAQ i can now see the animation set and its working just fine. terribly sorry for causing all noise and thanks for the help and fixes. much appreciated :)
