### ISSUE TITLE
Addon cannot be enabled on blender 4

### ISSUE THREAD

**Issue by EM4Volts** [DarklightGames/io_scene_psk_psa#66]
**Versions**
Blender: 4.0.0
io_scene_psk_psa: 6.1

**Describe the bug**
Addon cant be enabled, gives error message

**To Reproduce**
1. Press install in addons tab
2. enable addon

**Expected behavior**
the addon should be enabled

**Screenshots**
![Screenshot 2024-01-22 022858](https://github.com/DarklightGames/io_scene_psk_psa/assets/87427011/f3fe374a-a318-4de2-b03f-a32fab782b48)

**Files**
Please post attachments of the PSK and/or PSA files that you are using to encounter the bug, if any.

**Additional context**

**Comment by cmbasnett** [comment]
I think you probably downloaded the wrong file. You should use the downloads links on the release page: https://github.com/DarklightGames/io_scene_psk_psa/releases/latest

**Comment by cmbasnett** [comment]
I am unable to reproduce this on my machine. If it's not too much to ask, would you be able to record a video using OBS to show me how you're installing it from start to finish (downloading to installing)?

**Comment by EM4Volts** [comment]
> I am unable to reproduce this on my machine. If it's not too much to ask, would you be able to record a video using OBS to show me how you're installing it from start to finish (downloading to installing)?

i dont know what the problem was but i reinstalled blender and it installed fine, my guess is that some old addon files caused this to happen.
