### ISSUE TITLE
Custom normals not being imported

### ISSUE THREAD

**Issue by festivities** [DarklightGames/io_scene_psk_psa#67]
**Versions**
Blender: 3.6.1
io_scene_psk_psa: Latest commit

**Describe the bug**
Importing a model with supposed custom normals doesn't work. I've included a screenshot of what it should look like comparing this add-on with Befzz' PSK importer. Also unrelated but I don't think importing shape keys works either - that may be a skill issue on my part though since it's not being imported with both add-ons anyway.

**Screenshots**
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/77230051/db77bfa9-1bef-43c9-8661-385c04418e62)
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/77230051/ff3e69ec-05a9-465e-bd78-e0bd18eec381)

**Files**
https://files.catbox.moe/ivi6wc.psk

**Additional context**
The model's from the game Wuthering Waves. I've made sure that `Vertex Normals` is ticked during the import process.

**Comment by cmbasnett** [comment]
You can see the custom normals by toggling auto-smooth on the mesh data.

https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/df5440b3-e7f3-4c93-88e9-5726ab63a155

This is however very unintuitive, so I have made a change that will automatically enable auto-smooth for models that import with custom normals (https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.1.2).
