### ISSUE TITLE
Load file doesnt work 6.1.1

### ISSUE THREAD

**Issue by Minimoi4321** [DarklightGames/io_scene_psk_psa#68]
6.1.1
Blender: (4.0)
io_scene_psk_psa: (6.1.1)

Describe the bug:
I can't install the addons

To Reproduce:
install normaly the addons but at the end i does nothing.

**Files**
I think on init.py is empty, because i check it and i see nothing.
I tried with the older one 6.1.0 and its work.

**Additional context**
My "game file" isn't on the same drive that c:\

**Comment by cmbasnett** [comment]
I just tested this on a fresh install and it works fine. Please follow the installation instructions here: https://github.com/DarklightGames/io_scene_psk_psa#installation . Also make sure to uninstall any existing versions of the addon.
