### ISSUE TITLE
psa import failure

### ISSUE THREAD

**Issue by Dx2AV** [DarklightGames/io_scene_psk_psa#69]
Hey there,

I know this might sound a bit dumb, but I'm really struggling with fixing this problem:

![Screenshot 2024-01-28 155245](https://github.com/DarklightGames/io_scene_psk_psa/assets/112660297/e40d1295-8b90-40be-bf98-af4850991cef)

What i did to avoid the issue (kinda):
So, the only way I found around it was to use a different plugin to import the animation (psa). But the issue with that plugin is, it only brings in the skeleton, not the mesh. Then, I apply the animation to the skeleton and export it as "seanim." After that, I apply the seanim to the psk model using the same plugin. It kind of works, but there are some problems in the animation itself, like messed-up keyframes and positions.

I'm not sure if it's a problem with the plugin or something I'm doing, but it seems like the plugin is copying the existing bones and adding "_end" to their names. This leads to the error I mentioned above. If anyone could help me out, that would mean a lot.

ps: this is what i mean with '_end' at the end of the bone {

[UseTranslationBoneNames]
root
pelvis
spine_01
spine_02
spine_03
clavicle_l
upperarm_l
lowerarm_l
hand_l
index_01_l
index_02_l
index_03_l
index_03_l_end <-- here
middle_01_l
middle_02_l
middle_03_l
middle_03_l_end <-- here
pinky_01_l
pinky_02_l
pinky_03_l
pinky_03_l_end <-- here
ring_01_l
ring_02_l
ring_03_l
ring_03_l_end <-- here
thumb_01_l
thumb_02_l
thumb_03_l
thumb_03_l_end <-- here
Weapon_l
Weapon_l_end <-- here
hyd_left_hand_a
hyd_left_hand_c
hyd_left_hand_c_end <-- here
hyd_left2_hand_a
hyd_left2_hand_c
hyd_left2_hand_c_end <-- here
lowerarm_twist_l
lowerarm_twist_l_end <-- here
hyd_left_hand_target
hyd_left_hand_target_end <-- here
hyd_left_hand_b
hyd_left_hand_b_end <-- here
hyd_left2_hand_target
hyd_left2_hand_target_end <-- here
hyd_left2_hand_b
hyd_left2_hand_b_end <-- here
clavicle_r
upperarm_r
lowerarm_r
hand_r
index_01_r
index_02_r
index_03_r
index_03_r_end <-- here
middle_01_r
middle_02_r
middle_03_r
middle_03_r_end <-- here
pinky_01_r
pinky_02_r
pinky_03_r
pinky_03_r_end <-- here
ring_01_r
ring_02_r
ring_03_r
ring_03_r_end <-- here
thumb_01_r
thumb_02_r
thumb_03_r
thumb_03_r_end <-- here
Weapon_r
Weapon_r_end <-- here
lowerarm_twist_r
lowerarm_twist_r_end <-- here
scarf_02
scarf_03
scarf_04
scarf_05
scarf_06
scarf_06_end <-- here
neck_01
head
head_end <-- here
thigh_l
calf_l
foot_l
ball_l
ball_l_end <-- here
thigh_r
calf_r
foot_r
ball_r
ball_r_end <-- here
Bone_001
Bone_002
Bone_003
Bone_003_end <-- here
Bone_005
Bone_006
Bone_007
Bone_008
Bone_008_end <-- here
}

**Comment by cmbasnett** [comment]
This is a warning, not an error. The PSA animations have still been imported.

**Comment by Dx2AV** [comment]
> This is a warning, not an error. The PSA animations have still been imported.

but if i may ask, how can i actually see the animation itself?

**Comment by cmbasnett** [comment]
@Dx2AV https://github.com/DarklightGames/io_scene_psk_psa#why-cant-i-see-the-animations-imported-from-my-psa
