### ISSUE TITLE
Issue with importing/using framerates other than exported framerate

### ISSUE THREAD

**Issue by Dyvinia** [DarklightGames/io_scene_psk_psa#70]
**Versions**
Blender: 4.0
io_scene_psk_psa: 6.1.1

**Describe the bug**

**To Reproduce**
1. Import model and animation, set framerate during import or during scene to a different than default value
2. Play animation

**Expected behavior**
In 'in between frames', the character does an incorrect movement sometimes (so if animation is 30 and its interpolated to be 60fps, the frames in between the normal 30fps animation have a chance to have a completely wrong pose)

**Screenshots**
(**Spoilers for the game Jedi: Survivor**) https://imgur.com/PaHt1kt
(Ignore the cloth/cape, it was baked at 30fps and i didnt rebake it for the 60fps used in the gif)

**Files**
psa and psk file for character (animation fps is 30)
[test.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/14077582/test.zip)

**Additional context**
Happens both when using blender's frame interpolation and when setting the the addon's animation fps. Happens when importing as samples as well

**Comment by cmbasnett** [comment]
I had a look at it, and I don't believe this is an issue with the addon.

**Comment by cmbasnett** [comment]
The graph data itself exposes that this is case of the individual values of the quaternion being linearly interpolated on the inter-key frames. A "real" solution (that the game engine does) would be to do a spherical interpolation on the rotation data for inter-frame data. This would also fix the issue of the keyframes data not being aligned to the frame intervals.

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/f2fd84cf-4b92-4a0d-80ba-8bc34fcef241)

**Comment by cmbasnett** [comment]
I've made a fix locally that appears to work to resolve your issue. I'm able to resample the animation you sent to me at 90fps with no interpolation issues. I just need to do some more testing and improve the performance a bit before I release it.

**Comment by cmbasnett** [comment]
This has now been fixed in [v6.2.1](https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.2.1). Please try this out and let me know how it goes. This also fixes the positioning of the root bone as well.
