### ISSUE TITLE
RuntimeError: internal error setting the array

### ISSUE THREAD

**Issue by wh1techel** [DarklightGames/io_scene_psk_psa#72]
![b0myhjgcz2s](https://github.com/DarklightGames/io_scene_psk_psa/assets/158588695/eebf053b-0623-44de-abf5-3f00ffac6aaa)
![fel2LXuqZmg](https://github.com/DarklightGames/io_scene_psk_psa/assets/158588695/0727254a-2567-4bb4-8a39-320d85735379)
![to-tsnhs1Wg](https://github.com/DarklightGames/io_scene_psk_psa/assets/158588695/cab9e085-1e7f-421c-9372-803060a619b5)

**Comment by cmbasnett** [comment]
I have a pending fix for this coming later today.

**Comment by cmbasnett** [comment]
@wh1techel Please send the file that results in the error so I can verify that it is in fact fixed.

**Comment by cmbasnett** [comment]
This has been fixed and is now in release [6.1.2](https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.1.2).
