### ISSUE TITLE
Unable to import PSA with extra bones compared to PSK

### ISSUE THREAD

**Issue by coyotezin** [DarklightGames/io_scene_psk_psa#73]
**Versions**
Blender: 4.0.2
io_scene_psk_psa: 6.1.2

**Describe the bug**
Not being able to import a PSA animation that has extra bones compared to the PSK model.
It says "Imported 1 action with 1 warning" mentioning "The armature 'x' is missing **_number_** bones that exist in the PSA"
but no animation is loaded

**To Reproduce**
Import an animation that has leaf bones into a model that doesnt have leaf bones, pretty much the situation that im dealing with. 

**Expected behavior**
Ideally i would like to be able to import it anyway and just have it ignore(not import) the animation data related to the bones that the PSK doesnt have

**Comment by cmbasnett** [comment]
Your animations have been successfully imported. The warning is a warning, not an error. The animations are not applied to the armature upon import. See [here](https://github.com/DarklightGames/io_scene_psk_psa?tab=readme-ov-file#why-cant-i-see-the-animations-imported-from-my-psa).

> Ideally i would like to be able to import it anyway and just have it ignore(not import) the animation data related to the bones that the PSK doesnt have

This is already the current behavior.
