### ISSUE TITLE
Unable to export PSK with more than 256 Bones

### ISSUE THREAD

**Issue by 2oybean** [DarklightGames/io_scene_psk_psa#74]
**Versions**
Blender: 4.0
io_scene_psk_psa: 6.1.2

**Describe the bug**
Upon trying to export a PSK file with 290 bones (as imported) I am met with the error "Number of bones (290) exceeds limit of 256"

**To Reproduce**
1. Import PSK Model with more than 256 bones
2. Attempt to export the same model with or without any changes made

**Expected behavior**
PSK model to be exported as a less bone-heavy model would be

**Files**

[SK_Moxxi.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/14228128/SK_Moxxi.zip)

**Comment by cmbasnett** [comment]
This has been fixed in 82eaddf1cb66e747c264b829f7d2857801dc78fc. I will push out a new hotfix later today that includes this fix.

**Comment by cmbasnett** [comment]
This has been fixed in [6.2.0](https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.2.0).
