### ISSUE TITLE
Scale Down on Import

### ISSUE THREAD

**Issue by munchyfly** [DarklightGames/io_scene_psk_psa#75]
**Is your feature request related to a problem? Please describe.**

Meshes are imported on a huge scale. I understand that this is normal but working with meshes on such a large scale is something I try to avoid and I work with FBX exporting all the time.

**Describe the solution you'd like**

If possible, add a Scale Down option on import like [Befzz's](https://github.com/Befzz/blender3d_import_psk_psa) addon

**Describe alternatives you've considered**
Having two separate portable Blender installations: one with your addon and one with Befzzz's.

**Comment by cmbasnett** [comment]
This was implemented recently in 6.1.2 (https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.1.2).

**Comment by munchyfly** [comment]
Unfortunately that's for Blender 4 is it not? Oh well.. Thanks for answering :D

**Comment by cmbasnett** [comment]
Yes it's only for Blender 4. I am not adding new features to older versions of the add-on as it would create too large a maintenance burden.

**Comment by munchyfly** [comment]
No worries. I have both 3.6 and 4 installed so I can alternate between Befzz and yours for some stuff 😄 

Also, sorry to necro a closed issue. It's somewhat related to this one and I didn't want to start a new issue. I already sound like I'm asking too much so I apologize in advance:

I don't work much with PSAs, other than using them for weight painting and rendering GUI stuff in Mass Effect. Which is why I haven't abandoned Befzz completely yet, as when it imports PSAs, it imports already scaled to my mesh and armature.

I was wondering, if possible of course, if there's a way to add an option to scale down the PSA on import like PSKs as you added, since I use FBX so much.

This is a quirk of mine so of course, only if it doesn't give too much trouble and if it's possible. I've zero knowledge in coding 😂 .

Thanks for reading and for your work 😄

**Comment by cmbasnett** [comment]
I'm afraid I'm not really understanding the process here or what is going on with the files you're using.

I am presuming that you are taking in assets from Mass Effect, modifying them and exporting them back out, is that right?

If that's the case then I don't know why you would need to be modifying the scaling of anything, or using FBX for that matter. Perhaps you could better explain your process and why it is that you think you need to be scaling things up and down.

**Comment by munchyfly** [comment]
FBX helps with non-vanilla meshes. Meshes break for me when exporting as PSK if they are non-vanilla. It's also easier for me to work with when it's scaled down.

When importing PSA with your addon, the animation imports with no issues and even with it's UDK size which I know is normal. But when I apply the action to my mesh, it stretches the mesh.

Like I said, I only use PSA for GUI rendering and weighting. So it's just a quirk of mine.

**Comment by cmbasnett** [comment]
> It's also easier for me to work with when it's scaled down.

This is what I'm questioning. In what way is it easier? The scaling is arbitrary and various settings can be tweaked within Blender to have things work better for the scale of the scene you're working in, such as the Clip Start & Clip End in the View panel.

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/f89498fc-f8ce-431b-8f8c-ed0683a3abd4)


> Like I said, I only use PSA for GUI rendering and weighting. So it's just a quirk of mine.

I don't really understand this, the PSA is for skeletal mesh animations, how does that help wthi GUI rendering and weighting?

**Comment by munchyfly** [comment]
I'll just change the scene units then if I use 4.0

Thanks for your time and patience :)
