### ISSUE TITLE
Psa animation does not appear

### ISSUE THREAD

**Issue by 4rtb** [DarklightGames/io_scene_psk_psa#81]
**Versions**
Blender: (3.6 and 4.0)
io_scene_psk_psa: (6.1.0 for blender 4.0 and 5.0.5 for blender 3.6)

**Describe the bug**
Psa animation does not appear

**To Reproduce**
1. Import psa animation

**Expected behavior**
Psa animation is superimposed on the selected skeleton and played

**Files**
https://www.mediafire.com/folder/wijpgkjinz0zl/Character-Assets

**Additional context (video)**
https://mihailbajrakov311.wistia.com/medias/030z7w09mt

**Comment by cmbasnett** [comment]
This is not a bug. This is intended behavior, as is [mentioned in the README](https://github.com/DarklightGames/io_scene_psk_psa?tab=readme-ov-file#why-cant-i-see-the-animations-imported-from-my-psa).
