### ISSUE TITLE
Commandline?

### ISSUE THREAD

**Issue by mrfrankito** [DarklightGames/io_scene_psk_psa#82]
Is there a command line I can use in order to import files from a python script?
For example this:
# Replace 'import_function' with the actual function from Blender or an addon
bpy.ops.import_scene.import_function(filepath=file_path)

**Comment by cmbasnett** [comment]
`bpy.ops.import_scene.psk` is the name of the function. You can see the list of arguments as properties [here](https://github.com/DarklightGames/io_scene_psk_psa/blob/master/io_scene_psk_psa/psk/import_/operators.py#L14).

For example:

```
bpy.ops.import_scene.psk(filepath='your://filepath', should_import_vertex_colors=False, scale=3.0)
```
