### ISSUE TITLE
missing python dll 3.11??

### ISSUE THREAD

**Issue by resinate** [DarklightGames/io_scene_psk_psa#84]
installed version 6.2.0 says errors with python

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/185112/05e2b7db-0d04-4b4d-9d4d-b3ddb405cb3d)

**Comment by resinate** [comment]
also to note theres no mention of requiring python to be installed, might wanna add details on it

**Comment by cmbasnett** [comment]
Python is included as a part of Blender, there is no need to do a separate install. This error seems to indicate that your Python is trying to link against Python 3.11 which is not right since Blender 4.0 uses 3.10. Were you messing with your Blender's Python install?

**Comment by resinate** [comment]
i just installed blender 4.0 from main site thats it

**Comment by cmbasnett** [comment]
See the [compatibility table](https://github.com/DarklightGames/io_scene_psk_psa?tab=readme-ov-file#compatibility) here.  I also have 4.0.2 installed as well and the add-on works just fine. I suspect something is going haywire with your Blender or system configuration that causes it to try to use Python 3.11.

Open the Python Console in 4.0.2 and make sure it reads out with the following:

```
PYTHON INTERACTIVE CONSOLE 3.10.13 (main, Sep 20 2023, 07:33:17) [MSC v.1928 64 bit (AMD64)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, gpu, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data
```

**Comment by resinate** [comment]
the issue is, cuz i have SVP installed which i use to watch all my movies on, i wont uninstall it
