### ISSUE TITLE
Blender 4.1 deprecated Auto Smooth

### ISSUE THREAD

**Issue by fclivaz42** [DarklightGames/io_scene_psk_psa#86]
**Versions**
Blender: 4.1
io_scene_psk_psa: 6.2.0

**Describe the bug**
Since Blender 4.1 deprecated Auto Smooth, the plugin becomes unusable when importing meshes that have split normals/use autosmooth.

**To Reproduce**
Try to import any PSK that has split normals/uses autosmooth.

**Expected behavior**
There should be a workaround to use autosmooth as per this thread: https://projects.blender.org/blender/blender/pulls/108014

**Screenshots**
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/95506988/9ee91160-b755-4d09-8444-dc30b1308241)

**Files**
None.

**Additional context**
I linked the PR removing the use_auto_smooth API call, which explains a few other things. If you need more information please let me know!

**Comment by cmbasnett** [comment]
I've already addressed this on the Blender 4.1 branch (https://github.com/DarklightGames/io_scene_psk_psa/tree/blender-4.1). It will be released as the latest version when it is released.

**Comment by fclivaz42** [comment]
My bad, didnt see this earlier! appreciate it.

have a nice day :)

**Comment by cmbasnett** [comment]
@fclivaz42  A new version has been issue that works with Blender 4.1: https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/7.0.0
