### ISSUE TITLE
Import material missing

### ISSUE THREAD

**Issue by StormtrooperLawyer** [DarklightGames/io_scene_psk_psa#91]
Hello there!
I'm having a weird issue where when I import a animation mesh it will have one material slot for some reason. Tried a couple of things but none did the trick. 
Can someone help with it perhaps?

I'm using the latest version of the addon and with the recommended version of blender alongside it.
The game I'm importing it into is Star Wars Republic Commando.

**Comment by colinbasnettskyboxlabs** [comment]
Please send me the relevant files so I can recreate the issue you're having. Blend files, PSK etc.

**Comment by StormtrooperLawyer** [comment]
> Please send me the relevant files so I can recreate the issue you're having. Blend files, PSK etc.

Thank you man for looking into this!
Here's the link to the .blend 

Fyi I don't know how much this matters but we are replacing the model in game .

**Comment by cmbasnett** [comment]
You've made the Drive link private. You can just drag and drop the .blend file in here as an attachment.

**Comment by StormtrooperLawyer** [comment]
> You've made the Drive link private. You can just drag and drop the .blend file in here as an attachment.

Hey sorry man for the late reply but I was at work but I have you access to the link earlier so it should work.

**Comment by cmbasnett** [comment]
As far as I can tell, this is working correctly on the add-on side. I can export this as a PSK, then re-import it and both materials are still there. I suspect, perhaps, that whatever engine you're importing this into doesn't like the fact that the name of the materials has spaces in it. Try changing the name of the materials to not contain spaces and let me know how it goes.

**Comment by StormtrooperLawyer** [comment]
> As far as I can tell, this is working correctly on the add-on side. I can export this as a PSK, then re-import it and both materials are still there. I suspect, perhaps, that whatever engine you're importing this into doesn't like the fact that the name of the materials has spaces in it. Try changing the name of the materials to not contain spaces and let me know how it goes.

Hey man we tried changing the material name to one without spaces and that is shorter but to no avail, still one material will slot will show up in the game editor. :(

**Comment by cmbasnett** [comment]
If this is the case then I suspect something may be wrong with the importer in the engine. I'm going to close this as this isn't an issue with the addon.
