### ISSUE TITLE
Certain Bones not Animating properly after import of PSA file.

### ISSUE THREAD

**Issue by bnthomason** [DarklightGames/io_scene_psk_psa#94]
**Versions**
Blender: 4.1
io_scene_psk_psa:  latest (7.0.0)

**Describe the bug**
Importing the psk and psa file will result in the hair bones not animating properly. Before you say "Your animations have been successfully imported. The warning is a warning, not an error. The animations are not applied to the armature upon import.", I am aware the animations successfully imported, and are in the action editor. I can see most the animations working in the Action editor, except for the hair; It does not animate with the rest of the model.

**To Reproduce**
1`. Open Blender 4.1
2. Import AN_NPC_MOB_Unicorn_A01_SK_KHS.psk
3. Import AN_NPC_MOB_Unicorn_A01_AS_KHS.psa

**Expected behavior**
In theory, importing the psk file should not have any dummy bones, or importing the psa file should correlate the dummy bone and all of it's childs.

**Screenshots**
![Bone Parenting Issue](https://github.com/DarklightGames/io_scene_psk_psa/assets/68030747/47db50ff-a2eb-49fc-98ce-4485c36ec3fb)
![Parent Dummy01](https://github.com/DarklightGames/io_scene_psk_psa/assets/68030747/77e62cfd-8642-4cfd-8efc-007a920828fb)

**Files**
[AnimSet.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/15490300/AnimSet.zip)
Animset file includes the psk and psa file.

**Additional context**
This may be a model problem, the way I exported this model a long time ago. I no longer have access to the original untouched files, so if it is indeed a model problem and you know how to fix bones or know a tutorial that explains how to do this, please tell me! Thanks!

**Comment by cmbasnett** [comment]
The issue here is that the PSK and PSA armatures are fundamentally incompatible.

One possible solution would be to allow the user to simply import the armature bones from the PSA, since it seems like all the armature data is present there. I'll see about adding this.

**Comment by cmbasnett** [comment]
Actually, just checked and the PSA files do not have sufficient information to reconstruct the armature, it just has the bone names. Unfortunately, this means that it's also impossible to somehow infer what changes should be made to the PSK armature based on the PSA data. Unfortunately, there's nothing that the addon can do to help you here.

**Comment by bnthomason** [comment]
I see. Thanks for your effort anyway. I managed to find the original files on an old hard drive backup. I'll see if I can get them exported again. If I have more problems with PSK importing I'll let you know here.
