### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by EdwardGrave** [DarklightGames/io_scene_psk_psa#97]
**Versions**
Blender: 4.1
io_scene_psk_psa: 7.0.0

**Describe the bug**
can't enable the addon

**To Reproduce**
1. Open Blender 4.1
2. Navigate to the Blender Preferences (Edit > Preferences).
3. Select the Add-ons tab.
4. Click the Install... button.
5. elect the .zip file that you downloaded earlier and click Install Add-on.
6. Enable the newly added Import-Export: PSK/PSA Importer/Exporter addon

**Expected behavior**
addon is enabled and I can impor PSK files

**Screenshots**
![Blender Screen log 2](https://github.com/DarklightGames/io_scene_psk_psa/assets/32829453/02bca642-95cb-4b36-90b5-8cd70777420b)
![Blender Screen log 1](https://github.com/DarklightGames/io_scene_psk_psa/assets/32829453/0de86b01-cb67-4ade-badc-555d8e214a47)

https://github.com/DarklightGames/io_scene_psk_psa/assets/32829453/ef3c1b43-e3d5-4ede-b97f-d9d26a2e9a02

**Comment by NOOTLORD** [comment]
Try installing blender 4.1.1 this versions works for me 👍

**Comment by cmbasnett** [comment]
@EdwardGrave Are you still encountering this issue?

**Comment by cmbasnett** [comment]
This can happen if you are importing multiple versions of the same addon, since the namespaces are shared. I suggest uninstalling any versions of this addon and re-installing it again. I'm going to close this since it is not an issue with the addon.
